Task3
TShatov/react-edu pull request #4
Opened 2023-01-17 15:23 UTC by TShatov

При нажатии на кнопку Add to Cart в карточке продукта - у неё увеличивается индикатор, какое количество данной позиции мы хотим купить. Но вот "запушить" это количество в массив productsInCart... я не пойму как. Пробовал различными путями, но так и не вышло.

2023-01-17 15:29 UTC, AndModestov commented on src/ShopContainer.js
> +        addProduct: this.addProduct
Где у тебя эта функция определена?

2023-01-17 15:32 UTC, AndModestov commented on src/components/AddToCartButton.js
> +    this.state = { productAmount: 0 };
Тебе зачем тут состояние? Ты этот стэйт хранишь в ShopContainer, туда и пиши

2023-01-17 15:35 UTC, AndModestov commented on src/components/AddToCartButton.js
> +  }
Подсказку насчет этого я тебе давал, определи эту функцию в ShopContainer.
Тут ты меняешь локальное состояние компонента AddToCart, а тебе нужно менять глобальное состояние хранящееся в ShopContainer, если ты хочешь чтобы это состояние было доступно во всех остальных компонентах

2023-01-17 16:03 UTC, AndModestov commented on src/ShopContainer.js
> +      </ShoppingCartContext.Provider>
если сделаешь его враппером, то тут вместо компонентов указываешь 
{this.props.children}

2023-01-17 16:07 UTC, AndModestov commented on index.css
> +}
В этом файле можешь оставить общие вещи, типа body, p, span, button - общие генеральные стили короче.
Если определяешь стили конкретного компонента (юproduct-card) - делай файл со стилями внутри папки компонента

2023-01-17 16:12 UTC, TShatov commented on src/ShopContainer.js
> +      </ShoppingCartContext.Provider>
Вот этот момент не совсем понял...

2023-01-17 16:13 UTC, AndModestov commented on src/components/ProductCard.js
>            alt={this.props.title}/>
TextBox, Price и Image компоненты должны быть внутри папки компонента ProductCart, т.к они относятся только к нему

2023-01-17 16:17 UTC, AndModestov commented on src/components/AddToCartButton.js
> +            );
Вот тут еще можешь добавить какой нибудь инпут для увеличения количества.

2023-01-17 16:20 UTC, AndModestov commented on src/ShopContainer.js
> +  }
эта функция простая, если ты для товара кнопку нажмешь 5 раз - она накидает тебе 5 объектов в массив, хотя по сути должна менять количество для одного.
Как с остальным закончишь - модифицируй ее таким образом, чтобы она проверяла добавлен ли уже продукт в productsInCart. Если добавлен - должна просто менять количество. Если не добавлен - добавлять.

2023-01-18 08:19 UTC, AndModestov commented on src/ShopContainer.js
> +      </ShoppingCartContext.Provider>
https://github.com/TShatov/react-edu/pull/4#discussion_r1072397071

2023-01-18 12:52 UTC, AndModestov commented on index.css
> +}
Этот класс относится к SHoppingCart

2023-01-18 12:52 UTC, AndModestov commented on index.css
> +}
И этот

2023-01-18 13:09 UTC, AndModestov requested changes
Чекни комменты, нужно еще подпилить

2023-01-18 13:09 UTC, AndModestov commented on index.css
> +}
Этот класс относится к SрoppingCart компоненту

2023-01-18 13:09 UTC, AndModestov commented on index.css
> +}
И этот

2023-01-18 13:09 UTC, AndModestov commented on index.css
> +}
И эти три выше

2023-01-18 13:09 UTC, AndModestov commented on index.css
> +}
2 класса выше относятся к компоненту каталога

2023-01-18 13:09 UTC, AndModestov commented on index.js
> +import './src/index.js';
Не нужен тебе index.js в src. Перенеси все его содержимое сюда

2023-01-18 13:09 UTC, AndModestov commented on src/components/Catalog.js
> +import ProductCard from './ProductCard/index';
просто `import ProductCard from './ProductCard'`, импортер по умолчаню будет index.js файл искать

2023-01-18 13:09 UTC, AndModestov commented on src/components/ProductCard/AddToCartButton.js
> +import ShoppingCartContext from '../../contexts/ShoppingCartContext';
не надо релативных импортов, '../../' плохая практика.
```
import products from 'src/constants/Products';
import ShoppingCartContext from 'src/contexts/ShoppingCartContext';
```
или `~/src` вместо src, точно не помню сработает ли первый вариант

2023-01-18 13:09 UTC, AndModestov commented on src/components/ProductCard/ProductCard.css
> +
Не надо шрифт импортировать каждый раз, достаточно один раз в корневом css файле

2023-01-18 13:09 UTC, AndModestov commented on src/components/ProductCard/index.js
> +import React, { Component } from 'react';
Импорт реакта всегда идет первой строчкой. Если ты запустишь eslint - он наверняка будет ругаться

2023-01-18 13:09 UTC, AndModestov commented on src/components/ProductCard/index.js
> +            alt={this.props.title}/>
Формат
```
<Image
    ...
    ...
/>
```

2023-01-18 13:09 UTC, AndModestov commented on src/components/ShopProvider.js
> +import ShoppingCartContext from '../contexts/ShoppingCartContext';
`import ShoppingCartContext from 'src/contexts/ShoppingCartContext';`

2023-01-18 13:09 UTC, AndModestov commented on src/components/ShoppingCart.js
> +import ShoppingCartContext from '../contexts/ShoppingCartContext';
то же самое

2023-01-18 13:09 UTC, AndModestov commented on src/components/ShoppingCart.js
> +};
Это зачем?

2023-01-18 13:09 UTC, AndModestov commented on src/components/ShoppingCart.js
> +                <p>Shopping Bag: ({productsInCart.length})</p>
Ты бы отрендерил их не количеством, а списком каким то, чтобы понимать что все данные товара у тебя здесь доступны

2023-01-18 13:09 UTC, AndModestov commented on src/index.js
> +);
Переноси это все в корневой index.js

2023-01-18 14:37 UTC, AndModestov commented on src/components/ProductCard/AddToCartButton.js
> +import products from '../../constants/Products';
Зачем ты все продукты тут импортируешь? Ты сразу весь список что ли хочешь в корзину добавлять?

2023-01-18 14:38 UTC, AndModestov commented on src/components/ProductCard/AddToCartButton.js
> +  constructor(props) {
В этот компонент должен быть передан 1 продукт, 1 конкретный продукт который ты в корзину добавляешь

2023-01-18 14:39 UTC, AndModestov commented on src/components/ProductCard/AddToCartButton.js
> +                <button onClick={() => addProduct(products, quantity)}>Add to Cart</button>
Вот здесь ты сам понял что делаешь?) Ты передаешь в функцию AddProducts полный список продуктов

2023-01-20 10:07 UTC, AndModestov commented on src/components/ProductCard/AddToCartButton.js
> +                <button onClick={() => addProduct(this.props, this.quantity)}>Add to Cart</button>
Там лишних props-ов нет?

2023-01-20 10:08 UTC, AndModestov commented on src/components/ProductCard/AddToCartButton.js
> +                <button onClick={() => addProduct(this.props, this.quantity)}>Add to Cart</button>
this.props.product?

2023-01-20 10:09 UTC, AndModestov commented on src/components/ShoppingCart.js
> +                    productsInCart.map((product, amount) => (
Переименуй в cartItem, product.product выглядит как то не оч

2023-02-08 13:58 UTC, merged