Task4
TShatov/react-edu pull request #5
Opened 2023-02-09 21:46 UTC by TShatov

2023-02-10 07:05 UTC, AndModestov requested changes
1. Поле количества игнорируется при добавлении в корзину.
https://user-images.githubusercontent.com/14037358/218024405-b6b6f021-06d4-4fdb-984f-5ee7c40c9a95.mov

2. Каунтер добавленных товаров работает немного неверно, чекни коммент выше

3. Добавление в корзину надо модифицировать. Если в корзине уже есть товар - то он не должен добавляться отдельной строкой, он просто должен инкрементить счетчик имеющейся строки.
<img width="1440" alt="Снимок экрана 2023-02-10 в 09 59 05" src="https://user-images.githubusercontent.com/14037358/218024606-2e0a583e-a308-446c-b8d9-35bdb7e44dbf.png">

4. Зазор странныйб надо убрать 
<img width="1440" alt="Снимок экрана 2023-02-10 в 09 58 37" src="https://user-images.githubusercontent.com/14037358/218024923-1c31124f-7a57-4849-ba89-4e9361274be2.png">


В остальном хорошо вроде) Поправльб потом еще посмотрю

2023-02-10 07:05 UTC, AndModestov commented on index.js
> +  <ShopProvider >
Убери пробел в конце.
```
<ShopProvider>
  ...
</ShopProvider>
```
Когда тэг самозакрывающий то:
`<ShopProvider />`

2023-02-10 07:05 UTC, AndModestov commented on src/components/MainMenu.js
> +                    <li><NavLink to={cartPath()}>Cart ({productsInCart.length})</NavLink></li>
productsInCart.length дает тебе количество объектов. Но у каждого объекта счетчик есть. Соответственно тебе нужна сумма всех amount-ов а не length

2023-02-10 07:05 UTC, AndModestov commented on src/routes/Product.js
> +};
Как попасть на эту страницу?

2023-02-10 07:05 UTC, AndModestov commented on src/routes/index.js
> +export default [ Main, Product, Cart, Contacts, NotFound ];
Пробелы по краям массива не ставятся

2023-02-13 16:06 UTC, AndModestov commented on src/components/MainMenu.js
> +    }
Функцию ты не туда сунул, ты уж опирайся на тот код что уже написал)
```
class MainMenu extends Component {
  constructor(props) {
    super(props);

    this.calculateSum = this.calculateSum.bind(this);
  }

  calculateSum(products) {
    return arr.reduce((accumulator, object) => {
      return accumulator + object.salary;
    }, 0);
  }
  
  render() {
    ....
    ....
    <>{this.calculateSum(productsInCart)}</>
 }
```

2023-02-13 16:07 UTC, AndModestov commented on src/components/ShopProvider.js
> +    if (index == -1) {
===, три равно

2023-02-13 16:13 UTC, AndModestov commented on src/components/ShopProvider.js
> +      });
Во первых, ты опять в функции-поисковике пытаешься вычисления делать. Почитай внимательно доки, как работает find и findIndex. Это не forEach, findIndex возвращает index, а find возвращает сам объект. Внтури блока у ни указывается УСЛОВИЕ поискаб никогда там никаких вычислений и присваиваний не делай

Во вторых, нахрена тебе find если у тебя индекс есть уже:
productsInCart[index].amount += 1;

this.setState({ productsInCart }) вынеси за if-else

2023-02-13 16:15 UTC, AndModestov commented on src/components/views/Cart/index.js
> +                      <li key={itemKey}>{cartItem.product.title}<span>Amount: {cartItem.amount}</span></li>
Вот это что значит все?) Вроде нужно вернуть как было

2023-02-13 17:00 UTC, TShatov commented on src/components/views/Cart/index.js
> +                      <li key={itemKey}>{cartItem.product.title}<span>Amount: {cartItem.amount}</span></li>
если в качестве ключа использовать product.id, то React потом ругается на НЕ уникальность элементов в списке...как только назначил вместо ключа некий itemKey - перестал ругаться...

2023-02-13 17:28 UTC, TShatov commented on src/routes/Product.js
> +};
В задании было пока только просто создать эту страницу...

2023-02-14 07:42 UTC, AndModestov commented on src/components/views/Cart/index.js
> +                      <li key={itemKey}>{cartItem.product.title}<span>Amount: {cartItem.amount}</span></li>
Ты назначен не некий itemKey, второй элемент в итераторе это индекс, им лучше не пользоваться так, только если альтернативы нет.
product.id зависит от тебя, задай уникальные айди всем продуктам в списке своемб просто 1,2,3,4

2023-02-14 07:45 UTC, TShatov commented on src/components/views/Cart/index.js
> +                      <li key={itemKey}>{cartItem.product.title}<span>Amount: {cartItem.amount}</span></li>
Точно! Оно же давало ошибку, потому что тогда список создавался хоть бесконечный из одинаковых элементов, а я же поправил! Косяяяк, ща будет ))

2023-02-14 08:28 UTC, AndModestov requested changes
1. Пара стилистических недочетов, см. комменты. Не забывай запускать линтер прежде чем пушить.
2. input количества все еще не работает как положено
<img width="800" alt="Снимок экрана 2023-02-14 в 11 23 46" src="https://user-images.githubusercontent.com/14037358/218679524-0ba3b42f-b078-43f3-8f38-a133240a8ef2.png">
3. Не понятно для чего тебе компонент Main если по сути это каталог и есть. Конвертируй его в Catalog

2023-02-14 08:28 UTC, AndModestov commented on src/components/MainMenu.js
> +import { mainPath, cartPath, contactsPath} from '~src/helpers/routes';
Пробела нехватает в конце. Не забывай запускать линтер

2023-02-14 08:28 UTC, AndModestov commented on src/components/MainMenu.js
> +    return products.reduce( (acc, curObj) => {
лишний пробел

2023-02-14 08:28 UTC, AndModestov commented on src/components/ShopProvider.js
> +    const index = productsInCart.findIndex( currentIndex => currentIndex.product.id === product.id);
лишний пробел после скобки

2023-02-14 12:22 UTC, merged