Task5
TShatov/react-edu pull request #6
Opened 2023-03-15 13:26 UTC by TShatov

2023-03-16 13:47 UTC, AndModestov requested changes
Смотри комменты

2023-03-16 13:47 UTC, AndModestov commented on src/components/Slideshow.js
> +
перемести всю эту портянку с запросом в отдельный файл api.js, хотя бы примерно так:
```
const makeRequest = attrs => request
  .set('Authorization', `Bearer: ${accessToken}`)
  .get(...)
  .query(attrs);
  
const fetchImages = () => makeRequest({'content_type': 'images'})
  .then(() => ...)
```
Вообще существует правило такое, DRY называется - don't repeat yourself. Явно повторяющийся код надо переиспользовать.

2023-03-16 13:47 UTC, AndModestov commented on src/components/Slideshow.js
> +      .then(({ body: { items } }) => {
декомпозируй сильнее, дальше ты везде копаешь до gallery каждый раз items[0].fields.gallery

2023-03-16 13:47 UTC, AndModestov commented on src/components/Slideshow.js
> +      });
this.setState({ images: gallery });
this.setState({ currentImage: gallery[0].url })

2023-03-16 13:47 UTC, AndModestov commented on src/components/Slideshow.js
> +  }
не надо тебе else тут.
```
if (slideshowCounter == 0) return;
...
```

Вот это тоже должно сократиться если последуешь советам выше:
this.state.images[0].fields.gallery[slideshowCounter].url;

2023-03-16 13:47 UTC, AndModestov commented on src/components/Slideshow.js
> +          <img onLoad={this.slideshowImage()} className='slideshow-image' src={this.state.currentImage} />
Можно и так, а можно setInterval определить в componentDidMount и этот setInterval будет менять currentImage

2023-03-16 13:47 UTC, AndModestov commented on src/components/views/Main/index.js
> +  }
То же самое, этой партянке запроса здесь не место

2023-03-16 13:47 UTC, AndModestov commented on src/components/views/Product/index.js
> +  }
аналогично

2023-03-16 13:47 UTC, AndModestov commented on yarn-error.log
> +      at processTicksAndRejections (node:internal/process/task_queues:83:21)
Этот файл в игнор

2023-03-21 21:22 UTC, TShatov commented on src/components/Slideshow.js
> +          <img onLoad={this.slideshowImage()} className='slideshow-image' src={this.state.currentImage} />
Да, так больше даже понравилось, стабильнее, чем через onload

2023-03-22 13:39 UTC, AndModestov requested changes
В целом хорошо, но чекай комменты)

2023-03-22 13:39 UTC, AndModestov commented on src/components/Slideshow.js
> +    }
if (slideshowCounter == 0) return;

В одну строку. В других местах тоже поменяй

2023-03-22 13:39 UTC, AndModestov commented on yarn-error.log
> +      at processTicksAndRejections (node:internal/process/task_queues:83:21)
Удали этот файл из репозитория

2023-03-22 13:39 UTC, AndModestov commented on src/helpers/api.js
> +const accessToken = 'R4FhPbGLGH4OrEfOi4RDTw-19pCcDYV6hLcZZxbMNX4';
Если сделаешь такое в каком нибудь тестовом задании - заругают.
Нельзя хранить публичные ключи в репозитории.
Настрой .env и перенеси туда.
https://stackoverflow.com/questions/48699820/how-do-i-hide-an-api-key-in-create-react-app

2023-03-22 13:39 UTC, AndModestov commented on src/components/views/Main/index.js
> +    makeRequest({'content_type': 'product'})
не надо ключ в кавычки заключать, просто content_type: 'product'

2023-03-22 13:39 UTC, AndModestov commented on src/components/views/Product/index.js
> +  }
<img width="1440" alt="Снимок экрана 2023-03-22 в 16 32 16" src="https://user-images.githubusercontent.com/14037358/226920826-1d3672a0-6a5b-46d9-b602-06966bdad3e5.png">

2023-03-22 13:39 UTC, AndModestov commented on src/components/views/Product/index.js
> +  }
Еще раз. Ты с бэкэнда получаешь 3 продукта, нахрена тебе тут 3 продукта? Тебе нужно чтобы с бэкэнда пришел 1 ПРОДУКТ, c нужным id. Ты получаешь список сейчас, а должен получать 1 запись, это другой эндпоинт должен быть, посмотри со стороны api как получить 1 запись

2023-04-06 16:11 UTC, AndModestov commented on yarn-error.log
> +      at processTicksAndRejections (node:internal/process/task_queues:83:21)
git rm --cached <file>, убери файл из гита этот

2023-04-06 17:28 UTC, merged